export const REDUCER_ACTIONS = {
  SET_USER_DETAILS: "SET_USER_DETAILS",
  SET_REGISTER_DETAILS: "SET_REGISTER_DETAILS",
  SET_LOGIN_DETAILS: "SET_LOGIN_DETAILS",
  SET_UPLOAD_GIFT_DETAILS: 'SET_UPLOAD_GIFT_DETAILS'
};
